site_name: Curso POO com Java
site_url: https://profmatheusrosa.github.io/curso-poo-java/
site_description: Curso completo de Programação Orientada a Objetos com Java.
site_author: Prof. Matheus Rosa

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
  features:
    - navigation.instant  # Deixa a navegação mais rápida
    - navigation.top      # Adiciona botão "voltar ao topo"
    - search.highlight    # Destaca os termos buscados
    - search.suggest      # Sugere palavras enquanto digita
    - content.action.edit # Botão para sugerir edições no GitHub

nav:
  - Início: index.md
  - Introdução: introducao.md
  - Conceitos Básicos:
      - Classes e Objetos: conceitos-basicos/classes-objetos.md
      - Atributos e Métodos: conceitos-basicos/atributos-metodos.md
  - Pilares da POO:
      - Encapsulamento: pilares-poo/encapsulamento.md
      - Herança: pilares-poo/heranca.md
      - Polimorfismo: pilares-poo/polimorfismo.md
  - Avançado:
      - Interfaces: avancado/interfaces.md
      - Classes Abstratas: avancado/classes-abstratas.md

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - footnotes
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/profmatheusrosa/curso-poo-java

extra_footer: |
  <div style="text-align: center;">
    © 2025 Prof. Matheus Rosa - Todos os direitos reservados
  </div>  